default_chain: stride-testnet
chains:
  gaia-testnet:
    key: gaia-key
    chain-id: GAIA
    rpc-addr: http://127.0.0.1:26617      
    grpc-addr: http://127.0.0.1:9890     
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /data/vol1/stride-snap/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: stride-key
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://127.0.0.1:26457      
    grpc-addr: http://127.0.0.1:9490     
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /data/vol1/stride-snap/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
